ci: update gallery error

diff --git a/.github/workflows/ci.yml b/.github/workflows/ci.yml
--- a/.github/workflows/ci.yml
+++ b/.github/workflows/ci.yml
@@ -96,5 +96,6 @@ jobs:
           if [[ `git status --porcelain` ]]; then
             echo "Gallery config is up to date."
           else
-            core.setFailed("The gallery is out of date, run `yarn update-gallery-config`")
+            echo "::error file={name},line={line}::The gallery is out of date, run `yarn update-gallery-config`"
+            exit 1
           fi
