chore: update ci

diff --git a/.github/workflows/ci.yml b/.github/workflows/ci.yml
--- a/.github/workflows/ci.yml
+++ b/.github/workflows/ci.yml
@@ -94,7 +94,8 @@ jobs:
         run: |
           yarn update-gallery-config
           if [[ -z $(git status --porcelain) ]]; then
-            core.setFailed('The gallery is out of date, run `yarn update-gallery-config`')
+            echo "::error ::The gallery is out of date, run `yarn update-gallery-config`"
+            exit 1
           else
             echo "Gallery config is up to date."
           fi
